OOP school library: add basic UI
obibaadoma/School_Library pull request #4
Opened 2023-10-05 22:53 UTC by obibaadoma

# Project Requirements

## `app.rb` Console Application

1. Create an `app.rb` file as the console app entry point.

## Methods in `app.rb`

2. Implement methods in `app.rb` to perform the following actions:
   - List all books.
   - List all people.
   - Create persons (teachers/students).
   - Create a book.
   - Create a rental.
   - List rentals for a given person ID.

## `main.rb` Entry Point

3. Define the `main` method in `main.rb` for user interaction.
   - Present a list of options to the user.
   - Allow users to choose an option.
   - If necessary, collect input parameters.
   - Provide a way to gracefully quit the app.

2023-10-06 03:36 UTC, rloterh reviewed
Hi Derek, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented; The _Key Features_ section of your ReadMe should include features related to your project. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-10-06 08:35 UTC, DammyShittu requested changes
Hi @obibaadoma,

## Highlights
✔️ App exits

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-06 08:35 UTC, DammyShittu commented on main.rb
> +Main
- [ ] Kindly run your app and ensure it works before submitting it for review. None of these options works at all. From options 1 to 6. Only exiting the app, option 7, works.

  I cannot create people, books or rentals. I cannot list any of them either. None works at all. See example of error message.

  ![image](https://github.com/obibaadoma/School_Library/assets/54848363/86cd354b-562a-482d-abd7-9e5b9133d585)

2023-10-06 22:42 UTC, Alusp requested changes
Hi @obibaadoma , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![close](https://media.giphy.com/media/RjQ68u1NIlcL47cCN0/giphy.gif)

 ## Highlights
✔️ Good PR Summary. ✔️
 ✔️ Completed most of the TASKS ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alusp in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-06 22:47 UTC, Alusp commented on app.rb
> +      puts '3. Create person'
- [ ] Good implementing te cane, however, I ran into error after running your project, please resolve

![Re_Review](https://github.com/obibaadoma/School_Library/assets/43528594/83d344cf-55fb-42e4-acc0-e6a28ea02db2)

2023-10-07 13:51 UTC, gemmen29 approved these changes
Hi @obibaadoma, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-07 14:07 UTC, merged